jobs:
  include:
    - stage: commit
      language: generic  
      script:
        - "export TRAVIS_COMMIT_MSG=\"$(git log -n 1 --skip=1 --pretty=format:%s)\""
        - echo $TRAVIS_COMMIT_MSG
        - ( [[ $TRAVIS_COMMIT_MSG =~ ^\[(repo|ardu|andr|docs)\]\ ([a-zA-Z0-9\ \(\)]*)$ ]] && echo "Commit message matches pattern" ) || { echo "Commit message DOES NOT match pattern"; exit -1; } 
    - stage: arduino
      language: c
      install:
        - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16" 
        - sleep 3
        - export DISPLAY=:1.0
        - wget https://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
        - tar xf arduino-1.8.5-linux64.tar.xz
        - sudo mv arduino-1.8.5 /usr/local/share/arduino
        - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
        - arduino --install-library ArduinoSTL
      script:
        - arduino --verify --board arduino:avr:mega:cpu=atmega2560 $TRAVIS_BUILD_DIR/sistema-embebido/sistema-embebido.ino
branches:
  only: 
    - master
notifications:
  email:
    on_success: always
    on_failure: always
